export enum HTTP_STATUS_CODE {
  CONTINUE = 100,
  SWITCHING_PROTOCOLS = 101,
  PROCESSING = 102,
  EARLY_HINTS = 103,
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NON_AUTHORITATIVE_INFORMATION = 203,
  NO_CONTENT = 204,
  RESET_CONTENT = 205,
  PARTIAL_CONTENT = 206,
  MULTI_STATUS = 207,
  ALREADY_REPORTED = 208,
  IM_USED = 226,
  MULTIPLE_CHOICES = 300,
  MOVED_PERMANENTLY = 301,
  FOUND = 302,
  SEE_OTHER = 303,
  NOT_MODIFIED = 304,
  USE_PROXY = 305,
  UNUSED = 306,
  TEMPORARY_REDIRECT = 307,
  PERMANENT_REDIRECT = 308,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  PAYMENT_REQUIRED = 402,
  FORBIDDEN = 403,
  NOTFOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  NOT_ACCEPTABLE = 406,
  PROXY_AUTHENTICATION_REQUIRED = 407,
  REQUEST_TIMEOUT = 408,
  CONFLICT = 409,
  GONE = 410,
  LENGTH_REQUIRED = 411,
  PRECONDITION_FAILED = 412,
  PAYLOAD_TOO_LARGE = 413,
  URI_TOO_LONG = 414,
  UNSUPPORTED_MEDIA_TYPE = 415,
  RANGE_NOT_SATISFIABLE = 416,
  EXPECTATION_FAILED = 417,
  IM_A_TEAPOT = 418,
  MISDIRECTED_REQUEST = 421,
  UNPROCESSABLE_ENTITY = 422,
  LOCKED = 423,
  FAILED_DEPENDENCY = 424,
  TOO_EARLY = 425,
  UPGRADE_REQUIRED = 426,
  PRECONDITION_REQUIRED = 428,
  TOO_MANY_REQUESTS = 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
  UNAVAILABLE_FOR_LEGAL_REASONS = 451,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
  HTTP_VERSION_NOT_SUPPORTED = 505,
  VARIANT_ALSO_NEGOTIATES = 506,
  INSUFFICIENT_STORAGE = 507,
  LOOP_DETECTED = 508,
  NOT_EXTENDED = 510,
  NETWORK_AUTHENTICATION_REQUIRED = 511,
}

export const DEFAULT_USER_AVATAR =
  'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png';

export const PHONE_REGEX = /0[0-9]{9}/;

export const FORMAT_NUMBER_REGEX = /\B(?=(\d{3})+(?!\d))/g;

export const COLOR_CHART = {
  BITTER_LEMON: '#B5E612',
  MALACHITE: '#00D06C',
  PAOLO_VERONESE_GREEN: '#0A9882',
  TURQUOISE_SURF: '#05B4C9',
  CERULEAN_FROST: '#6699C3',
  PLUMP_PURPLE: '#6847A7',
  PURPUREUS: '#9B43AC',
  JAZZBERRY_JAM: '#A01865',
  CERISE: '#EB3269',
  SUNSET_ORANGE: '#FF5D56',
  ORANGE: '#F7A300',
  METALLIC_YELLOW: '#FECD10',
  CRAYOLA: '#1AB369',
  RADICAL_RED: '#FA3363',
};

export const ORDER: { [key: string]: string } = {
  descend: 'desc',
  ascend: 'asc',
  '': '',
};

export const TEXT_RECENT_DATA = 'recent_data';

export enum TIME_FILTER {
  '24H' = '24h',
  '7D' = '7d',
  '1M' = '1m',
}

export const TIME_FILTER_ALL = [
  {
    key: '1d',
    label: '24h',
  },
  {
    key: '7d',
    label: '7d',
  },
  {
    key: '1m',
    label: '1m',
  },
  {
    key: '3m',
    label: '3m',
  },
  {
    key: '6m',
    label: '6m',
  },
  {
    key: '1y',
    label: '1y',
  },
];

export const SOCKET_EVENTS = {
  coinChange: 'coinChange',
};

export enum TYPE_GLOBAL_SEARCH {
  Trending,
  Crypto,
  Category,
  Upcoming,
  Exchange,
  Launpatch,
  Funcraising,
  Backer,
  Unlock,
}
